service: claim-nft-serverless
org: erictenenbaum10

provider:
  name: aws
  stage: local
  region: "us-west-1"
  runtime: nodejs14.x
  environment:
    accountId: "#{AWS::AccountId}"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:GetItem
        - dynamodb:Query
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:${self:provider.environment.accountId}:table/NFTS"

functions:
  hashes:
    handler: claim.handler
    events:
      - http:
          path: /nft/{nftId}/claim/{claimToken}
          method: post
          private: false
          request:
            parameters:
              paths:
                nftId: true
                claimToken: true

resources:
  Resources:
    HashesDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: nftId
            AttributeType: S
        KeySchema:
          - AttributeName: nftId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: "NFTS"

plugins:
  - serverless-dotenv-plugin
  - serverless-dynamodb-local
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  serverless-offline:
    noPrependStageInUrl: true
  dynamodb:
    stages:
      - local
    start:
      port: 8000
      host: localhost
      inMemory: false
      dbPath: .
      migrate: true
      seed: true
      sharedDb: true
    seed:
      test:
        sources:
          - table: NFTS
            sources: [./data-examples/seed-data.json]
